name: Publish Dry Run
on: workflow_dispatch
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Publish to Maven Local
        run: ./gradlew clean publishAllPublicationsToMavenLocal --stacktrace
  deploy-docs:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build Dokka HTML
        run: ./gradlew dokkaHtmlMultiModule
